CREATE TABLE "recipe" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  "name" VARCHAR NOT NULL,
  "author" VARCHAR NOT NULL,
  "image" VARCHAR NOT NULL,
  "prep_time" VARCHAR NOT NULL,
  "cook_time" VARCHAR NOT NULL,
  "total_time" VARCHAR NOT NULL,
  "recipe_yield" VARCHAR NOT NULL,
  "description" TEXT NOT NULL,
  "json_ld" TEXT NOT NULL
);
CREATE TABLE "category" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  "name" VARCHAR NOT NULL
);
CREATE TABLE "recipe_category" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  "recipe_id" INTEGER NOT NULL,
  "category_id" INTEGER NOT NULL
);