version: "3"

services:
  rust:
    build:
      context: .
    container_name: "recipes_rust_dev"
    command: tail -f /dev/null
    volumes:
      - ../:/home/api
    ports:
      - 18000:8000
    working_dir: /home/api
    environment:
      DATABASE_URL: postgres://recipe_admin:nbFQm5ge4NHjeXLngGPt4B3WRiUbKTNTboFvbvHqLQCDCz6q@postgres/recipe
  postgres:
    image: postgres
    container_name: "recipes_postgres_dev"
    environment:
      POSTGRES_PASSWORD: nbFQm5ge4NHjeXLngGPt4B3WRiUbKTNTboFvbvHqLQCDCz6q
      POSTGRES_USER: recipe_admin
      POSTGRES_DB: recipe
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
      - ../postgresql-init/:/docker-entrypoint-initdb.d/
    ports:
      - 15432:5432

  adminer:
    container_name: "recipes_adminer_dev"
    image: adminer
    ports:
      - 18080:8080

volumes:
  postgres_data_dev:
