version: "3"

services:
  rust:
    build:
      context: .
    container_name: "rust_dev"
    command: tail -f /dev/null
    volumes:
      - ../:/home/api
    ports:
      - 8000:8000
    working_dir: /home/api
    environment:
      DATABASE_URL: postgres://recipe_admin:nbFQm5ge4NHjeXLngGPt4B3WRiUbKTNTboFvbvHqLQCDCz6q@postgres/recipe
      FRONTEND_URL: http://localhost:8000
  postgres:
    image: postgres
    container_name: "rust_dev_postgres"
    environment:
      POSTGRES_PASSWORD: nbFQm5ge4NHjeXLngGPt4B3WRiUbKTNTboFvbvHqLQCDCz6q
      POSTGRES_USER: recipe_admin
      POSTGRES_DB: recipe
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
      - ../postgresql-init/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  adminer:
    container_name: "rust_dev_adminer"
    image: adminer
    ports:
      - 8080:8080

volumes:
  postgres_data_dev:
